### ISSUE TITLE
Some files under /provisioning-workflows/WAS are unreadable

### ISSUE THREAD

**Issue by zhaocaih** [openmainframeproject/zorow#32]
Hi @Conner-IBM, I noticed that there are some files in /provisioning-workflows/**WAS** are unreadable, can you please check them?

1. All files under /provisioning-workflows/WAS/files
2. server_group_variables.properties under /provisioning-workflows/WAS/files
3. .template and .sh files under /provisioning-workflows/WAS/workflows

**Comment by Conner-IBM** [comment]
These files where imported from the WAS github:
https://github.com/WASdev/sample.zos.provision.was
The files are displayed the same way in both here in the zorow github, and the source WAS github.
The issue in readability is likely due to the workflow being designed to use files that are in a different encoding than github expects.

**Comment by shreeji818** [comment]
Please see comment by Conner. Closing the issue.
